name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore TeamSpeak3.Metrics.Web.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore TeamSpeak3.Metrics.Web.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal TeamSpeak3.Metrics.Web.sln

    - name: Publish
      if: ${{ github.ref == 'refs/heads/master' }}
      run: dotnet publish -c release -o ./app --no-restore TeamSpeak3.Metrics.Web.sln

    - name: Login to DockerHub
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker
      if: ${{ github.ref == 'refs/heads/master' }}
      run: | 
        docker build --pull -t prayzzz/teamspeak3-metrics-web:latest .
        docker push prayzzz/teamspeak3-metrics-web:latest

