name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Install dependencies
      run: dotnet restore TeamSpeak3.Metrics.Web.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal TeamSpeak3.Metrics.Web.sln

    - name: Publish
      run: dotnet publish -c release -o ./app --no-restore TeamSpeak3.Metrics.Web.sln

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker
      run: | 
        docker build --pull -t prayzzz/teamspeak3-metrics-web:latest -t prayzzz/teamspeak3-metrics-web:${{ env.RELEASE_VERSION }} .
        docker push prayzzz/teamspeak3-metrics-web:latest
        docker push prayzzz/teamspeak3-metrics-web:${{ env.RELEASE_VERSION }}

